//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osler.BusinessLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InsightsMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InsightsMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osler.BusinessLayer.InsightsMapping", typeof(InsightsMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.powerbi.com/view?r=eyJrIjoiMzcxM2ZjN2MtZDFmNy00MDg4LTlmZjEtNTdjM2M0YTJjNWQ5IiwidCI6ImM0OWEyMzk1LWQxNTMtNDljYy04MjA4LTAyMjQyNzQ1ZWYyMSIsImMiOjh9.
        /// </summary>
        internal static string BillableInsightImage {
            get {
                return ResourceManager.GetString("BillableInsightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.powerbi.com/view?r=eyJrIjoiMzcxM2ZjN2MtZDFmNy00MDg4LTlmZjEtNTdjM2M0YTJjNWQ5IiwidCI6ImM0OWEyMzk1LWQxNTMtNDljYy04MjA4LTAyMjQyNzQ1ZWYyMSIsImMiOjh9.
        /// </summary>
        internal static string BillableNonBillableInsightChart {
            get {
                return ResourceManager.GetString("BillableNonBillableInsightChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.powerbi.com/view?r=eyJrIjoiMzcxM2ZjN2MtZDFmNy00MDg4LTlmZjEtNTdjM2M0YTJjNWQ5IiwidCI6ImM0OWEyMzk1LWQxNTMtNDljYy04MjA4LTAyMjQyNzQ1ZWYyMSIsImMiOjh9.
        /// </summary>
        internal static string NonBillableInsightImage {
            get {
                return ResourceManager.GetString("NonBillableInsightImage", resourceCulture);
            }
        }
    }
}
